<?php 

$liste = ["67",
"76",
"42nd street",
"a blossomed tree",
"a sunny day",
"a taste of honey",
"a veranda moment",
"a.1",
"a.j.",
"a.m.",
"abate",
"abbey bells",
"abbey crusta",
"absinth",
"absolut 100 honey",
"absolut 50/50",
"absolut a/w 10",
"absolut apeach blimey",
"absolut apeach cosmopolitan",
"absolut apeach dream",
"absolut apeach mango",
"absolut apeach melba",
"absolut apeach melon",
"absolut apeach shooter",
"absolut apeach squeeze",
"absolut apeach surrender",
"absolut apeach toddy",
"absolut apeach tonix",
"absolut apeach top floor",
"absolut apeach zest",
"absolut aphrodisiac",
"absolut appearance",
"absolut asian ginger",
"absolut babe",
"absolut banana crush",
"absolut basil",
"absolut berri cola",
"absolut berri cosmo",
"absolut berri honey",
"absolut berry ball",
"absolut berry exotic",
"absolut bijou",
"absolut black 50",
"absolut black apple",
"absolut black basil",
"absolut black blooded mary",
"absolut black bloody mary",
"absolut black russian",
"absolut black vanilia",
"absolut blackberry bellini",
"absolut blackberry fruitini",
"absolut blood and sand",
"absolut bloody",
"absolut bloody burns",
"absolut blue bell",
"absolut blue pearl",
"absolut blues",
"absolut bonobo",
"absolut buck",
"absolut celebration",
"absolut cherry crush",
"absolut chocolate caipiroska",
"absolut chocolate chili martini",
"absolut chocolate martini",
"absolut chocolate pears",
"absolut cinnamango sour",
"absolut cranberry",
"absolut crimson pears",
"absolut crush",
"absolut easy breeze",
"absolut elder",
"absolut establishment",
"absolut forest crush",
"absolut fresh",
"absolut fuzzy martini",
"absolut ginger",
"absolut ginger pear",
"absolut gingerpear martini",
"absolut grcic madras",
"absolut grcic mayday martini",
"absolut grcic mono",
"absolut grcic north side cocktail",
"absolut grcic pearspresso",
"absolut green apple",
"absolut high tea",
"absolut hot black rasp",
"absolut hot blue rasp",
"absolut hot smith",
"absolut intrigue",
"absolut jabuticaba",
"absolut kurant scarlet",
"absolut mandrin breeze",
"absolut mandrin fizz",
"absolut mandrin madras",
"absolut mandrin rebel",
"absolut mandrin sour",
"absolut mandrin starlet",
"absolut mandrin zanzerac",
"absolut mandrinoska",
"absolut mango passion",
"absolut may be hot",
"absolut melon cup",
"absolut miami vice",
"absolut one source",
"absolut passion no. 2",
"absolut peachroska",
"absolut pears exotic",
"absolut pineapple mint",
"absolut plum",
"absolut ruby grape",
"absolut ruby sour no. 2",
"absolut smooth",
"absolut solstice",
"absolut strawberry",
"absolut sunbeam",
"absolut sweetsop",
"absolut trappy tea",
"absolut twister",
"absolut unboxed",
"absolut vanilia alexander",
"absolut vanilia avalanche",
"absolut vanilia breeze",
"absolut vanilia celebration",
"absolut vanilia cola",
"absolut vanilia flower",
"absolut vanilia fruit punch",
"absolut vanilia grasshopper",
"absolut vanilia iced tea",
"absolut vanilia in the city",
"absolut vanilia in the sky",
"absolut vanilia malted",
"absolut vanilia pop",
"absolut vanilia snap",
"absolut vanilia sunrise",
"absolut vanilia vain",
"absolut vanilla guava",
"absolut very berry",
"absolut watermelon",
"absolut wild cola",
"absolut wild cosmo",
"absolut wild cran",
"absolut wild iced tea",
"absolut wildflower",
"absolut yellow fever",
"absolutely bananas",
"ac",
"adam y eva",
"admiral",
"admiral (with whiskey)",
"affinity",
"agave collins",
"agent orange",
"agent orange 2",
"agma",
"alabama",
"alabama fizz",
"alabama slammer no 2",
"alabazam",
"alan's apple breeze",
"albemarle fizz",
"alcudia",
"aldin's retreat",
"alexander",
"alfonso",
"alfonso special",
"all stars",
"allegheny",
"allegria",
"alleluja",
"alley cat",
"alma",
"almond martini",
"almond old fashioned",
"almond'tini",
"amba 65",
"ambrosia",
"american",
"american beauty",
"american dream",
"american glory",
"amour crusta",
"amsterdam",
"amsterdam cobbler",
"andromeda",
"anejo highball",
"angelica",
"angel's face",
"angel's tip",
"aniara",
"aniversario",
"anno 1960",
"aphrodisiac (2)",
"apollo",
"appendicitis",
"appendicitis de luxe",
"appetizer",
"apple blossom",
"apple john",
"apple manhattan",
"apple pie vanilia",
"apple pilar",
"apricot lady",
"apricot mango martini",
"apricot pie",
"apricot sour",
"april in paris",
"april shower",
"aquabite",
"arnold palmer",
"blue lady",
"blue mediterranean",
"blue monday 2",
"blue moon",
"blue orchids",
"blue raspberry martini",
"blue riband",
"blue souvenir",
"blue temptation",
"blue train",
"blue virgin",
"blueberry and ginger fizz",
"blueberry daiquiri",
"blueberry martini",
"blueberry tea",
"blushin' russian",
"blushing bride",
"blushing monarch",
"bobbo's bride",
"bocci ball",
"bodybuilding",
"bolero",
"bolo",
"bolshoi punsch",
"bon bon",
"bone klistry",
"bonnie scot",
"boomerang i",
"boomerang ii",
"booming town",
"booster",
"bora bora",
"borden chase",
"border crossing",
"bossa nova 1",
"bossa nova 2",
"boston",
"boston gold",
"boston sidecar",
"boulevard",
"bourbon cobbler",
"bourbon cocktail",
"bourbon collins",
"bourbon lancer",
"bourbon sangaree",
"bourbon sling",
"bourbon sour",
"bowbells",
"bowling",
"boyd",
"brainstorm",
"bramble mimosa",
"brandy cocktail",
"brandy collins",
"brandy cooler",
"brandy crusta",
"brandy cuban",
"brandy daisy",
"brandy fino",
"brandy fix",
"brandy flip",
"brandy float",
"brandy highball",
"brandy pick me up",
"brandy plush",
"brandy sangaree",
"brandy smash",
"brandy sour",
"brandy teapunch",
"brandy toddy",
"brave bull",
"braw lad",
"brazen martini",
"brazil",
"brazilian berry",
"break even",
"breakfast",
"breakfast egg-nog",
"bric-a-brac",
"brilliant star",
"brim full of asha",
"british squirrel",
"broadway",
"broadway melody",
"broadway smile",
"broken spur",
"bronx",
"bronx empress",
"bronx golden",
"bronx silver",
"bronzing cooler",
"brown derby cocktail",
"brown university",
"brunette",
"bubble margarita",
"buck",
"bucks twizz",
"budapest by day",
"budapest by night",
"buddy",
"bull dog",
"bull shot",
"bull's blood",
"bunny bonanza",
"bunny hug",
"burnt toasted almond",
"bushranger",
"buster",
"butler coctail",
"butterfly flip",
"buttergrog",
"by invitation only",
"byrrh special",
"c c c",
"c.f.h. cocktail",
"caballo",
"cabaret",
"cable car",
"cablegram",
"café cobbler",
"café cointreau",
"café dom",
"café gloria",
"café greco",
"café impérial",
"café kirsch",
"café royal",
"caipirissima",
"caipiruva",
"cameron's kick",
"campari nobile",
"campeón",
"campexport",
"cape kennedy",
"capitol",
"caprice",
"caprilia",
"captain kidd",
"captains blood",
"caramel manhattan",
"caribbean royale",
"caribbean sensation",
"caribbean squirrel",
"caribbean sun",
"caribe",
"caricature cocktail",
"carine",
"chivas cooler",
"cinderella no.2",
"citron pressé",
"corpse reviver (no. blue)",
"czarina",
"d.o.m.",
"damson in distress",
"dandy",
"danny's special",
"darb",
"daredevil flip",
"darling",
"date at eight",
"davis",
"dawn crusta",
"deansgate",
"deauville",
"deceiver",
"delicia",
"delicious sour",
"delmonico",
"dempsey",
"depth bomb",
"desert",
"desert cooler",
"desert dream",
"desert healer",
"deshler cocktail.",
"dessalines",
"detached force",
"devil's kiss",
"devil's tail",
"devil's breath",
"devil's cocktail",
"devil's torch",
"di saronno punsch",
"diablo rouge",
"diabola",
"diamond fizz",
"diana",
"dianas bitter",
"dictador",
"diki-diki",
"dirty banana",
"dirty johnny",
"dirty white mother",
"discotheque",
"divan",
"dizzy izzy",
"dna",
"doctor",
"doctor coctail",
"doctor's special",
"doge",
"dolce havana",
"dolce vita",
"doll",
"dolores",
"dominican sunrise",
"don juan piña colada banana",
"don't go near the water",
"donkey's kick",
"donny",
"don't give up the ship",
"dorado",
"dorian gray",
"double diamond",
"double rainbow",
"douglas",
"draco",
"dracula's bite",
"dragon's breath",
"dream",
"dream cocktail",
"dream of naples",
"drink dada",
"dry cold deck",
"du barry",
"dulce maria",
"dummer junge",
"dunhill",
"dunlop",
"dutch courage",
"dying bastard",
"dynamo",
"e.t.",
"eagle",
"earthquake",
"easy does it",
"easy on the eyes",
"easy tiger",
"eclipse",
"ecstasy",
"ed's baby",
"eden",
"eden rocks",
"egg sour",
"egg-nog",
"eighth wonder",
"el chilenito",
"el floridita",
"el morocco",
"el presidente",
"el presidente 2",
"el toro",
"elderflower & pear martini",
"elk's own cocktail",
"ella",
"embassy cocktail",
"embassy royal",
"eminence",
"eminent",
"emmas campari",
"empire",
"errol flynn's pick-me-up",
"esquire",
"esquire martini",
"eton blazer",
"europa cup",
"exchequer",
"excise duty",
"exotic passion",
"extradition",
"faux 75",
"florida tonic",
"golden gleam",
"golden glow",
"golden queen",
"golden retriever",
"golden screw",
"golden slipper",
"golden spike",
"golden tulip",
"goldy rose",
"golf",
"good fellow",
"good night ladies",
"grainne",
"grand",
"grand duchess",
"grand marnier pick me up",
"grand passion",
"grand royal",
"grand smash",
"grand time",
"grande mimosa",
"granny's martini",
"grapefruit blossom",
"grapefruit tonic",
"graziella",
"green destiny",
"green fizz",
"green flash",
"green gatsby, the",
"green lady (in paris)",
"green rom",
"green ruby",
"green spree",
"green tea and mango splash",
"green tea martini",
"greenbriar",
"greenwich",
"greenwich fizz",
"grenadier",
"greta garbo cocktail",
"grog",
"gruszka royale",
"guldkant",
"gulf coast sex on the beach",
"gypsy 2",
"gypsy dancer",
"gypsy queen",
"habitant",
"haig special",
"haitian cocktail",
"haitian rum punch",
"hallelujah",
"halstead street velvet",
"happy honey cocktail",
"happy return",
"happy youth",
"harbour light",
"harlem nights",
"harlequin",
"harmony",
"harrity",
"harry lauder",
"harry's cocktail",
"harry's pick-me-up",
"harvard",
"harvest",
"hashi bashi",
"hasty",
"havana",
"havana sidecar",
"havanatheone",
"hawaii",
"hawaiian",
"hawaiian cocktail",
"hawaiian cosmopolitan",
"hawaiian stone sour",
"hazelito",
"head light",
"heart's desire",
"heather",
"heavy water",
"heavy water ii",
"hedgerow sling",
"hi ho cocktail",
"high brow",
"high hat",
"high heel",
"highland",
"highland lady",
"highroller",
"hiker",
"hiroshima",
"hock cup",
"hole in one",
"holland",
"holland house",
"homestead",
"honey bee",
"honey suckle",
"honeymoon",
"honeysuckle",
"honi honi",
"honolule",
"honolulu 2",
"honolulu juicer",
"honolulu one",
"honolulu silver",
"horsecar",
"hot brandy cider",
"hot breeze",
"hot buttered rum",
"hot himalaya express",
"hot italy",
"hot line",
"hot rhum punch",
"huberta",
"hudson bay",
"hummer",
"hunk martini",
"hunter",
"hunter's moon",
"huntsman, the",
"ignorance is bliss",
"iguana",
"illusion",
"imperial",
"imperial fizz",
"income tax",
"international stinger",
"island limeade",
"jasmine collins",
"lovely",
"lucky star",
"lugger",
"lumumba",
"luscious laura",
"lusitania",
"luxury",
"lychee cooler",
"m m p h",
"maartens mango martini",
"mabouhay",
"madame lou",
"madeira flip",
"madogs",
"mae west",
"mae west martini",
"magic trace",
"magnificent",
"maiden's blush cocktail",
"maiden's dream",
"maiden's prayer",
"mai-tai special",
"major",
"major bailey",
"make believe",
"make the grade",
"malcolm lowry",
"mali cooler",
"malibu and cranberry",
"malibu and lemon-lime soda",
"malibu and pineapple",
"malibu bajan congaline",
"malibu bridgetown breeze",
"malibu bullfisher",
"malibu cropover iced tea",
"malibu gold cup",
"malibu piña colada",
"malibu seabreeze",
"malibu st lawrence lemonade",
"malibu sugarmill kiss",
"malinatini",
"mambo",
"mambo king",
"mamie highball",
"mamie taylor",
"mamie's southern sister.",
"mancino",
"mandarino",
"mandrin bliss",
"mandrin cherry smash",
"mandrinoska",
"mandrintini",
"mango bellini",
"mango caliente",
"mango delight",
"mango no. 5",
"mango sling",
"manguito rico",
"maple leaf",
"mar de san remo",
"mar del plata",
"maragato",
"maragato special",
"marble hill",
"marco rye",
"marianne",
"mark seven",
"markee",
"marlene dietrich",
"marney",
"maroccan martini",
"marragansett",
"marshall de mure",
"marvel",
"marvin",
"mary of scotland",
"mary poppins",
"masquerade seabreeze",
"master of the hounds",
"mat the rat",
"mata hari martini",
"matilda",
"may blossom fizz",
"mayday martini",
"mayfair",
"mayfair martini",
"mazuma",
"mazzagran",
"mc martini",
"mcbrandy",
"mckinley's delight",
"mediterranean martini",
"mediterráneo",
"melba",
"memphis belle",
"merengue",
"merry k",
"merry widow",
"metropolis",
"metropolitan",
"metropolitan 1",
"mexico special",
"miami spice",
"million dollar cocktail",
"millionaire",
"millionaire royal",
"milvea",
"milwaukee",
"mint lemonade",
"orange and earl grey iced tea",
"pennsylvania",
"pepita",
"pepparmint frapé",
"perfect lady",
"perini",
"perú libre",
"peter pan",
"peter tower",
"pétion",
"petit pois",
"petite fleur",
"petroleum",
"peven",
"pharisäer",
"phoebe snow",
"pidge",
"piggelin",
"pineapple bronx",
"pineapple cobbler",
"pineapple cooler",
"pineapple fizz",
"ping-pong, german",
"pink gin",
"pink grapefruit fizz",
"pink hound",
"pink lady (original)",
"pink lady 2",
"pink lemonade",
"pink pearl",
"pink rose",
"pink tonic",
"pink tutu",
"pinky",
"pioneer",
"pippin",
"pitch-awoo",
"plaisir",
"planter's cocktail",
"plymouth chocolate gimlet",
"poinsetta",
"poker",
"polar bear",
"polar short cut",
"polar wind",
"polish martini",
"polish spring punch",
"polly",
"polly special",
"pollyanna",
"polo 2",
"polo dream",
"polonaise",
"polynesia",
"polynesian apple",
"pomegranate fizz",
"pomegranate, lime and tonic",
"pompanski martini",
"pool fool",
"poop deck",
"pop 65",
"port choc",
"port cobbler",
"port flip",
"porte cochére",
"porteo",
"posh punch",
"prado",
"prairie fire shooter",
"prairie oyster no. 1",
"presa diretta",
"presbyterian",
"president",
"president's pick, the",
"presidente",
"presto",
"prince",
"prince, italian",
"princess mary",
"princess mary's pride cocktail",
"princeton",
"prohibition punch",
"puerto apple",
"puertorican pink lady",
"pure raspberri",
"purple haze",
"purple hooter",
"pyl",
"quadruple orange martini",
"quadruplex",
"quaker's",
"quarter deck no. 1",
"quarter deck no. 2",
"quattro bianchi",
"quebec",
"queen bee",
"queen elizabeth",
"queen mary",
"queen of bahia",
"queen's cocktail",
"queen's peg",
"queen's smile",
"quelle vie",
"rainstorm",
"ramona cocktail",
"rapaska",
"raquel",
"raspberri fields forever",
"raspberry blimey",
"raspberry dream",
"raspberry fields forever",
"raspberry iced tea",
"raspberry mochatini",
"raspiroska",
"rattlesnake",
"ray long",
"raymond hitch cocktail",
"razzamataz",
"razzle dazzle",
"red devil",
"red earl martini",
"red flag",
"red hackle",
"red hope",
"red lion",
"red manhattan",
"red melontini",
"red tonic",
"redcoat",
"reef juice",
"regent star",
"remsen cooler",
"ritz",
"ritz cocktail",
"ritz fizz",
"riveredge",
"road streaker",
"roadster",
"rob roy perfect",
"rob roy sweet",
"robber",
"roy rogers",
"skylab",
"sledge hammer",
"sleepy head",
"slick",
"sloe dancer",
"sloe gin no. 2",
"sloe gin rickey",
"sloeberry",
"smile",
"smiling esther",
"smiling ivy",
"smiling through",
"smoothie",
"snake in the grass",
"snickers martini",
"snow white",
"snowball",
"so sunrise",
"sol de mayo",
"sonora",
"so-so",
"sour sun",
"south of the border",
"south pacific",
"south sea",
"south side",
"southampton",
"southern bride",
"southern cross",
"southern gin",
"southern ginger",
"southgate",
"sparkling galliano",
"sparkling orange",
"special fizz",
"special meridien",
"special rough",
"spencer",
"spiced absolut pears",
"spiced apple",
"spiced rum punch",
"spiced swizzle",
"spicy fifty",
"spicy mangotini",
"spina nera",
"spurt",
"sputnik",
"st clements",
"st. andrew's",
"st. clementine crush",
"stainless",
"stairs martini",
"stanford cocktail, the",
"stanley",
"star",
"starlight",
"starlight cocktail",
"stay sober",
"stilletto",
"stone fence",
"stonybrook",
"stork club cocktail",
"straits sling",
"strange weather",
"strawberry cocktail",
"strawberry delight",
"strawberry fizz",
"strawberry kick",
"strawberry kiss",
"strawberry night",
"strip-tease",
"stromboli",
"strong arm",
"stumble bum",
"submarine",
"submarino",
"suburban",
"sudret iced tea",
"suffering bastard",
"sugar daddy",
"suicide cocktail",
"summer rye",
"summer seen",
"summertime soda",
"sunflower highball",
"sunny dream",
"sunrise",
"sunriser",
"sunsplash",
"sunstroke",
"swan",
"swazi freeze",
"swedish highball",
"sweeney's",
"sweet air",
"swellegant",
"swinging oriental",
"t.e.e.",
"t.n.t.",
"t.v. special highball",
"tahiti club",
"tanglefoot",
"tao-tini",
"tatanka",
"tattoo special",
"tea for two",
"temperance punch",
"the lovely pear",
"virgin cup no.1",
"virgin espresso",
"virgin peach margarita",
"virgin pina colada",
"virgin royal hawaiian",
"virgin sangria",
"virgin strawberry daiquiri",
"watermelon lemonade",
"whispers-of-the-frost",
"whist",
"white",
"white baby",
"white plush",
"white rose",
"white shadow",
"white slave",
"white vanilia coffee",
"white way",
"whiz bang",
"whizz bang",
"whopee",
"will rogers",
"wilma",
"windsor rose",
"winner",
"winnie",
"witching eve",
"woodward",
"x y z",
"xanthia",
"xochimilco",
"yacht club",
"yang tze",
"yankee",
"yankee-dutch",
"yashmak",
"yellow daisy",
"yellow parrot",
"yellow plum",
"yellow submarine",
"yes and no",
"yo ho",
"yolanda",
"york",
"you and i",
"you never know",
"you only live twice",
"young man",
"zamboanga hummer",
"zaza",
"zentini",
"zoom",
"zumbo"];

echo json_encode($liste);